### ISSUE TITLE
Please add Y8 support if it is possible.

### ISSUE THREAD

**Issue by bxyhxyh** [sunnyone/Waifu2xAvisynth#2]
It's not an issue. But Y8 support would help to speed up things.
"Y8 is useful for processing RGB as individual planes. Sure one can use YV12 but it can be less efficient for slow filters."

Also we can use it only on luma and other scalers on chroma separately.

So... title.

**Comment by sunnyone** [comment]
The new version 0.0.2 supports Y8. Enjoy!

**Comment by sunnyone** [comment]
This release may discourage you because processing only Y8 probably improves the performance slightly. Originally the plugin just use the OpenCV's INTER_CUBIC filter for U/V planes, so the process is not slow (this behavior is the same as original waifu2x's).

**Comment by bxyhxyh** [comment]
Ok. Thank you.
